### ISSUE TITLE
Cannot find Python Pickle File

### ISSUE THREAD

**Issue by JcShang** [jjery2243542/adaptive_voice_conversion#12]
Hi, I am new to this field but try to run this for my recent research. However, after I changed the preprocessing config file, I still cannot run it. The error is missing python pickle file (e.g., train.pkl). Do you have some advice on how to generate or find the needed pickle files? Thanks a lot.

**Comment by JcShang** [comment]
Never mind

**Comment by zhu-ya** [comment]
Hello, I encountered the same problem. Could you please solve it? Can you tell me the solution? Thanks.
