### ISSUE TITLE
How to generate the pickle file(eg. train.pkl, in_test.pkl, out_test.pkl)?

### ISSUE THREAD

**Issue by JordanFan860406** [jjery2243542/adaptive_voice_conversion#16]
When I do the preprocessing, I get the error of  missing python pickle file
Can you give me some idea about how to generate pickle file ?
Thank you

**Comment by JordanFan860406** [comment]
> When I do the preprocessing, I get the error of missing python pickle file
> Can you give me some idea about how to generate pickle file ?
> Thank you

**Comment by jjery2243542** [comment]
Did you run the preprocessing?

**Comment by zhu-ya** [comment]
Hello, I encountered the same problem. Could you please solve it? Can you tell me the solution? Thanks.
