### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by ghost** [jjery2243542/adaptive_voice_conversion#2]
hi
can you add some doc, 
maybe just the commands I need to type to test?

**Comment by jjery2243542** [comment]
Hi, 
Thank you for your interest. I will add the documentations recently.

**Comment by Husnain08** [comment]
please add the documentation.

**Comment by jjery2243542** [comment]
Hi,
I am currently on a vacation, the code and documentation will be refined after I get back. Thank you for your interest.

**Comment by Husnain08** [comment]
okay. thanks.
