### ISSUE TITLE
Where is AdaIN?

### ISSUE THREAD

**Issue by sbkim052** [jjery2243542/adaptive_voice_conversion#21]
Looking at the model.py,,
In the decoder part, I can't find where AdaIN is. 
Can somebody tell me where it is used?

**Comment by jjery2243542** [comment]
https://github.com/jjery2243542/adaptive_voice_conversion/blob/master/model.py#L77

**Comment by sbkim052** [comment]
> https://github.com/jjery2243542/adaptive_voice_conversion/blob/master/model.py#L77

Thanks
