### ISSUE TITLE
Question about preprocessing

### ISSUE THREAD

**Issue by sbkim052** [jjery2243542/adaptive_voice_conversion#22]
Hi @jjery2243542 .
I have a question about preprocessing.

What is the role of the "sample_single_segments.py"?
####
    for i, utt_ind in enumerate(sample_utt_index_list):
        if i % 500 == 0:
            print(f'sample {i} samples')
        utt_id = utt_list[utt_ind]
        t = random.randint(0, len(data[utt_id]) - segment_size)
        samples.append((utt_id, t))
####
Especially i can't understand above part.

**Comment by jjery2243542** [comment]
During training, the model is trained on some fix length segments. This is to sample them.

**Comment by sbkim052** [comment]
Thank you @jjery2243542 .
Could you also tell me which code below is for? 
it's also in the preprocessing.py.

####
mel =np.dot(mel_basis, mag)
####

Why should we dot product the mel_basis and the mag?

**Comment by jjery2243542** [comment]
This is to convert linear scale spectrogram to mel scale.
