### ISSUE TITLE
some prolems about this repo

### ISSUE THREAD

**Issue by Pydataman** [jjery2243542/adaptive_voice_conversion#3]
1、in this paper "One-shot Voice Conversion by Separating Speaker and Content
Representations with Instance Normalization ", the architecture of the encoders and decode are different from the implementation of this repo.
2、in source code， what does this function LatentDiscriminator do?
3、when open the doc?

**Comment by jjery2243542** [comment]
Hi,
1. Please checkout to conv1d branch.
2. I used to try to use LatentDiscriminator to learning invariant representation like https://arxiv.org/abs/1804.02812.
3. Before the conference.
Thank you.
