### ISSUE TITLE
Urgent Issue --- Training does not start

### ISSUE THREAD

**Issue by Husnain08** [jjery2243542/adaptive_voice_conversion#7]
Hi @jjery2243542 ,
I tried to run this code. The preprocessing part runs successfully. In the training phase,  I am continously  getting  this error. Please help.
![Screenshot from 2019-08-27 09-14-32](https://user-images.githubusercontent.com/38109416/63740614-2e1b1380-c8ab-11e9-9100-2c32b17b7bd7.png)

**Comment by Husnain08** [comment]
@jjery2243542  can you please help with this?

**Comment by jjery2243542** [comment]
Hi,
I have updated. Please take a look. Thank you.

**Comment by Husnain08** [comment]
Look where ?
